[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/hubspot"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  included_files = ["netlify/functions/**"]

[functions."upload"]
  node_bundler = "esbuild"
